package com.example.client.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-22T22:05:14.749+08:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "myService",
                  wsdlLocation = "http://localhost:8081/service/my?wsdl",
                  targetNamespace = "http://manzj.net/services/test/wsdl")
public class MyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://manzj.net/services/test/wsdl", "myService");
    public final static QName MyServerSoapEndpoint = new QName("http://manzj.net/services/test/wsdl", "MyServerSoapEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/service/my?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/service/my?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserPortType
     */
    @WebEndpoint(name = "MyServerSoapEndpoint")
    public UserPortType getMyServerSoapEndpoint() {
        return super.getPort(MyServerSoapEndpoint, UserPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserPortType
     */
    @WebEndpoint(name = "MyServerSoapEndpoint")
    public UserPortType getMyServerSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(MyServerSoapEndpoint, UserPortType.class, features);
    }

}
