
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.demo.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-22T21:58:13.136+08:00
 * Generated source version: 3.3.3
 *
 */

@javax.jws.WebService(
                      serviceName = "myService",
                      portName = "MyServerSoapEndpoint",
                      targetNamespace = "http://manzj.net/services/test/wsdl",
                      wsdlLocation = "classpath:/xml/my/test.wsdl",
                      endpointInterface = "com.example.demo.test.UserPortType")

public class MyServerSoapEndpointImpl implements UserPortType {

    private static final Logger LOG = Logger.getLogger(MyServerSoapEndpointImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.demo.test.UserPortType#getName(com.example.demo.test.UserType user, com.example.demo.test.ReqHeaderType reqHeader, com.example.demo.test.RspHeaderType rspHeader)*
     */
    public com.example.demo.test.ResUserType getName(UserType user, ReqHeaderType reqHeader, javax.xml.ws.Holder<RspHeaderType> rspHeader) {
        LOG.info("Executing operation getName");
        try {
            com.example.demo.test.RspHeaderType rspHeaderValue = new RspHeaderType();
            rspHeaderValue.setMac("222222222");
            rspHeaderValue.setIp("127.0.0.1");
            rspHeaderValue.setAddress("http://localhost:8081");
            rspHeaderValue.setFrom("200");
            rspHeaderValue.setTo("100");
            rspHeader.value = rspHeaderValue;
            com.example.demo.test.ResUserType _return = new ResUserType();
            ResUserHeaderType resUserHeaderType = new ResUserHeaderType();
            resUserHeaderType.setFrom("200");
            resUserHeaderType.setTo("100");
            ResUserBodyType resUserBodyType = new ResUserBodyType();
            resUserBodyType.setSex("女");
            resUserBodyType.setAge(30);
            resUserBodyType.setUsername("李丽");
            _return.setHeader(resUserHeaderType);
            _return.setBody(resUserBodyType);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
