package com.example.demo.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-22T21:58:13.219+08:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://manzj.net/services/test/wsdl", name = "UserPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserPortType {

    @WebMethod(action = "urn://getName")
    @WebResult(name = "resUser", targetNamespace = "http://manzj.net/services/test", partName = "resUser")
    public ResUserType getName(

        @WebParam(partName = "User", name = "User", targetNamespace = "http://manzj.net/services/test")
        UserType user,
        @WebParam(partName = "ReqHeader", name = "ReqHeader", targetNamespace = "http://manzj.net/services/test", header = true)
        ReqHeaderType reqHeader,
        @WebParam(partName = "RspHeader", mode = WebParam.Mode.OUT, name = "RspHeader", targetNamespace = "http://manzj.net/services/test", header = true)
        javax.xml.ws.Holder<RspHeaderType> rspHeader
    );
}
